### ISSUE TITLE
Headings on main blog page

### ISSUE THREAD

**Issue by DeVil2O** [osdc/blog#21]
The headings are not written correct manner on main blog page. When you hit first heading scroll to the bottom it should be last.

**Comment by saranshbarua** [comment]
@DeVil2O I am not sure I understand your issue, can you please elaborate?

**Comment by DeVil2O** [comment]
![screenshot 18](https://user-images.githubusercontent.com/38765776/54045908-d273a580-41f8-11e9-8444-e969728ac7a3.png)
In this ss "How to open source" is on the first position.

**Comment by DeVil2O** [comment]
![screenshot 19](https://user-images.githubusercontent.com/38765776/54045966-fafb9f80-41f8-11e9-9521-bb942b853616.png)
But at the bottom of this page "How to open source" seems last.

**Comment by saranshbarua** [comment]
Ok, this seems like an issue. Would you like to work on this @DeVil2O ?

**Comment by ryzokuken** [comment]
This isn't something we do ourselves, the gatsby theme we use does things this way. The posts are listed in reverse chronological order (the latest ones first) and I think that's fine.

**Comment by saranshbarua** [comment]
@ryzokuken Ok, was confused by the post's title

**Comment by ryzokuken** [comment]
@saranshbarua no worries!

@DeVil2O thanks for this, but I don't think it could be fixed on our end. I'll close this but please feel free to reopen to open another issue if you find any persistent issues.
