### ISSUE TITLE
npm packages outdated

### ISSUE THREAD

**Issue by codekhal** [osdc/blog#24]
#### Description
It seems that the npm packages have been outdated and needs updation

#### Screenshots
![Screenshot from 2019-05-05 16-38-37](https://user-images.githubusercontent.com/32578541/57193124-85d8ec00-6f55-11e9-8a67-ceac10938979.png)

#### Files which needs Updation
* `package.json`
* `package-lock.json`

#### To Reproduce
Clone the repo then,
```
$ cd blog/
$ npm outdated
```

#### Additional Information
Beginners could take up this issue.

**Comment by codekhal** [comment]
Kindly review! Also, if you could add good-first-issue and other labels. @ryzokuken

**Comment by ryzokuken** [comment]
@codekhal thanks.

**Comment by sidntrivedi** [comment]
Fixed in #38. 🎉
