### ISSUE TITLE
Add CI to the Blog.

### ISSUE THREAD

**Issue by sidntrivedi** [osdc/blog#26]
We can discuss on this thread to either go for any CI like CircleCI / TravisCI for the blog or host it on Netlify.

/cc: @nightwarrior-xxx @saranshbarua @ryzokuken

**Comment by saranshbarua** [comment]
@sidntrivedi012 That's a good idea but before that, I think we should focus on getting more blogs on the floor. Design a proper strategy so that everyone knows about the blog and contributes to it. Because CI only makes sense if there are enough deployments.
Let me know what you think.

**Comment by sidntrivedi** [comment]
@saranshbarua +1. I guess we need to bring more people to contribute to blogs. Having done that, it would be viable to add CI/CD to it as there are already two more blogs here waiting to get built and its a overkill if someone has to manually do it everytime. CI would greatly reduce further effort.

**Comment by sidntrivedi** [comment]
But still, for now we can implement a CI here. Blogs will be written anyway. What do others think?

**Comment by ryzokuken** [comment]
I concur with @saranshbarua here. Not a lot of use pulling in CI if we don't have much content to begin with.

**Comment by sidntrivedi** [comment]
Sure. Then lets get more blogs to the floor and then maybe implement a CI pipeline. Thanks everyone. Closing this for now.
