### ISSUE TITLE
Regarding readme file

### ISSUE THREAD

**Issue by sickwiz** [osdc/blog#35]
In the **readme**  file , it is written that **node version 10 or below ** is required but I guess it should be 10 or above because I faced difficulties in node version 8.something.
If I am right, can I edit the readme?

**Comment by sidntrivedi** [comment]
Even I think it should be version 10 or above since the package.json file also mentions >=10 version. Please make a PR for it if possible. Thanks.

**Comment by sickwiz** [comment]
Sure.

**Comment by sidntrivedi** [comment]
Fixed in #36.
