### ISSUE TITLE
Remove dummy posts

### ISSUE THREAD

**Issue by saranshbarua** [osdc/blog#9]
Remove these posts

![screenshot from 2018-09-21 23-32-26](https://user-images.githubusercontent.com/23500643/45898154-bae56380-bdf6-11e8-8a2d-ebebee511aa1.png)

**Comment by HarendraSingh22** [comment]
Only removing the folders will do this,right?

**Comment by saranshbarua** [comment]
@HarendraSingh22 This is already resolved in #5 . I didn't notice it, my bad.

**Comment by saranshbarua** [comment]
Closing this.
